### ISSUE TITLE
KA10: Improper thread context for operation

### ISSUE THREAD

**Issue by larsbrinkhoff** [rcornwell/sims#53] opened 2018-03-08 06:34 UTC
There's a failure doing the final DUMP in the ITS build.  The error message is `Improper thread context for operation` and then the simulator dies.  Full log in https://travis-ci.org/PDP-10/its/jobs/350579354

I'll look into this, but I'm also posting it here in case you have any idea what it can be.

Log excerpt:

```
LIBMAX
   706 LIBMAX .FILE. (DIR)      0      3/7/2018 23:59:17.5
   707 LIBMAX DEFINE 65         2      3/7/2018 18:28:49
   708 LIBMAX DEFINE FASL       3      3/7/2018 23:55:28
   709 LIBMAX DEFINE UNFASL     3      3/7/2018 23:55:28
   710 LIBMAX DEFOPT 8          2      3/7/2018 18:28:49
   711 LIBMAX DEFOPT FASL       3      3/7/2018 23:54:54.5
   712 LIBMAX DEFOPT UNFASL     3      3/7/2018 23:54:54.5
   713 LIBMAX DISPLM 13         2      3/7/2018 18:28:49
   714 LIBMAX DISPLM 14         2      3/7/2018 18:28:49
   715 LIBMAX DISPLM FASL       3      3/7/2018 23:54:53.5
   716 LIBMAX DISPLM UNFASL     3      3/7/2018 23:54:53.5
   717 LIBMAX EDMAC  FASL       3      3/7/2018 23:54:58.5
   718 LIBMAX EDMAC  UNFASL     3      3/7/2018 23:54:58.5
   719 LIBMAX ERMSGC 210        2      3/7/2018 18:28:49
   720 LIBMAX ERMSGC FASL       3      3/7/2018 23:54:47
   721 LIBMAX ERMSGC UNFASL     3      3/7/2018 23:54:47Improper thread context for operation
expect: spawn id exp9 not open

**Comment by larsbrinkhoff** [comment] 2018-03-08 07:41
CC @eswenson1

**Comment by larsbrinkhoff** [comment] 2018-03-08 07:41
The message comes from sim_defs.h:

```
#define AIO_VALIDATE if (!pthread_equal ( pthread_self(), sim_asynch_main_threadid )) {sim_printf("Improper thread context for operation\n"); abort();}

**Comment by larsbrinkhoff** [comment] 2018-03-08 15:27
I disabled async I/O by passing `NOASYNCH=1` on the make command line.  But it didn't help.  It fails on the exact same place, just without the error message:

```
   718 LIBMAX EDMAC  UNFASL     3      3/8/2018 15:37:53.5
   719 LIBMAX ERMSGC 210        2      3/8/2018 07:22:22
   720 LIBMAX ERMSGC FASL       3      3/8/2018 15:37:29.5
   721 LIBMAX ERMSGC UNFASL     3      3/8/2018 15:37:29.5expect: spawn id exp8\
 not open
    while executing
"expect -exact $w"
    (procedure "respond" line 2)
    invoked from within
"respond "_" "rewind\r""

**Comment by rcornwell** [comment] 2018-03-08 16:31
I pulled down the default build and was unable to reproduce this... is there another branch or changes I need to make to reproduce this?

**Comment by larsbrinkhoff** [comment] 2018-03-08 16:46
Sorry, that's an important bit of information I forgot to add.

It's the ejs/ticket_710 branch.

**Comment by rcornwell** [comment] 2018-03-08 19:36
The problem is that DUMP is writing a record longer then 32K bytes. I was under the impression that dump would only write up to 5120 byte records.

**Comment by larsbrinkhoff** [comment] 2018-03-08 19:49
I'm not 100% sure how DUMP interacts with the tape drive.  I *believe* it just writes a stream of words and EOF marks.  ITS makes records.  Yes, they should be a maximum of 5120 bytes.

This could be a bug in the KA/KL file SYSTEM; MTAPE.  It seems the two KS10 build work fine.  KS10 uses SYSTEM; NMTAPE instead.

**Comment by rcornwell** [comment] 2018-03-08 20:56
Solved the problem... dump is dumping a zero length record.

**Comment by eswenson1** [comment] 2018-03-08 20:59
Great!  Does that mean that you know how to create a fix in SIMS that will allow these zero-length records to be dumped?  Will you be committing a change to tools/sims in the not-to-distant-future?

**Comment by rcornwell** [comment] 2018-03-08 21:08
I will be testing the changes tonight after work, and committing them. I need to make sure it does not break TOPS10.

**Comment by rcornwell** [comment] 2018-03-09 02:39
This should be fixed in current build.

**Comment by eswenson1** [comment] 2018-03-09 02:43
Very nice. Thanks.

**Comment by rcornwell** [comment] 2018-03-09 02:47
I am testing a version with latest SCP and display code.

**Closed** 2018-03-09 13:05 UTC
