### ISSUE TITLE
Dual CPU B5500 loops after Ctrl/E.

### ISSUE THREAD

**Issue by davygoat** [rcornwell/sims#8] opened 2017-12-23 15:37 UTC
Pressing Ctrl/E in CANDE sometimes causes the B5500 to go into a busy loop.

The problem can reliably be reproduced as follows:

- Add SET CPU1 ENABLED to xiii.ini.
- Start B5500 simulator, TSS/MCP XIII.
- Enter DT and TR at SPO.
- Enter CE to start CANDE.
- Telnet to port 2000, login as USER1.
- Enter LIST LOG/DISK command.
- While QUIKLST is running, press Ctrl/E. Repeat Ctrl/E a few times if necessary.
- Eventually MCP stops responding and CPU goes to 100%.
- killall -QUIT b5500 to produce core dump (copy attached).

This does not occur when CPU1 is disabled.

I am running latest B5500 on Slackware 14.2 on Intel Core i7 laptop.

[core.zip](https://github.com/rcornwell/sims/files/1584210/core.zip)

**Comment by rcornwell** [comment] 2017-12-23 16:41
Does this occur when running under DC/MCP? 

Does hitting Ctrl/E again cause the system to interrupt the simulation? 

During a quick test I was not able to reproduce this.

**Comment by davygoat** [comment] 2017-12-23 20:05
Hello Richard,


*Does this occur when running under DC/MCP?*

I don't think so. With MCP/DISK and INT/DISK I can telnet to port 2000 and
type some SPO commands by prefixing them with a question mark. In that
situation Ctrl/E only prints the station id "B5500 01/00". But I don't know
how to type a file from there (can't find any SPO command in Appendix C of
the Operations Manual for doing that). I've tried PD =, but Ctrl/E doesn't
cause it to loop there.

*Does hitting Ctrl/E again cause the system to interrupt the simulation?*

No. I'm doing this in a telnet'ed CANDE session, where Ctrl/E is the
equivalent of Ctrl/C. This is in a separate window from the SPO, so Ctrl/E
isn't going directly to the simulator. But whenever my problem occurs (in
CANDE/TSS), the SPO also stops responding, and hitting Ctrl/E there does
not interrupt the simulation as it normally does do.

*During a quick test I was not able to reproduce this.*

Annoying. Typical of a race condition. But it does do it every time on my
system. Is the second CPU implemented as a thread? I see scp uses a lot of
pthreads.


David.

**Comment by rcornwell** [comment] 2017-12-23 20:16
Let me do some more testing, I thought you were talking Ctrl/E at console, which would stop simulation.

**Comment by rcornwell** [comment] 2017-12-23 22:02
I pushed out a patch that allows for TS/MCP to be interrupted at the console with a ^E. This does not stop the bug, but prevents the simulator from being locked. I will need to research TS/MCP patches and see if I can either find a fix or see if I can figure out why the chain is getting looped to itself.

**Comment by rcornwell** [comment] 2018-07-27 17:04
This issues appears to be fixed in current build. ^E does not abort print out which is correct behavior. Fixed will be moved to simH main tree soon.

**Closed by rcornwell** 2018-07-27 17:04 UTC
Labels: bug
